### ISSUE TITLE
Model Unknown

### ISSUE THREAD

**Issue by priyanshisharma** [ShrideviReddy/Breast-Cancer-Prediction-API#2]
I understand that you are using the UCI dataset, but can you provide a little more information about the whereabouts of the model used?

**Comment by ShrideviReddy** [comment]
@priyanshisharma First of all thank you for updating URL. I have uploaded code (Breast cancer prediction ipynb file) in the repo.
I didn't do any fine tuning or compared performance of other algorithms,  since my goal was to build API using Flask and deploy on Heroku.

**Comment by ShrideviReddy** [comment]
Any suggestions are welcome.

**Comment by priyanshisharma** [comment]
My pleasure, got it, thank you 🎉 😄
